---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: billing
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgB1QacZIBNbCi1qZe199O77y3OXFa4EcBu6Thui9X4ZlObqfo8rR3YF3gkAstii644Qsn1yBrQQjzomlhG85ByM1j/wdp3nierAh6w5SLLR3H39rqV4bJIxXmuAXGkxg99fOJw6UN52i2lW4ZCncKPlIKZ2r26GPfzglUFm1x7x8Va8kvCsuUJvEh4sq0DI/TOYRjQVal175TxGE3j1j5Xmb4XbFw3DbiaGKKYvsSH2wkWX75brpjIBbQrkSG6axscVPSu24riVHEdpxGt2c6wBERnJo0ZCZO4g7PerR5Z8xRbt3/f5cV2Wmh8Q2Hxk9RU0CaHFUQ/TSy63C7d7OOWFDvwKsVN0veeQvqdZG7KGxLHTsCa64d3Rv2yGL+9ZMpv40KSGmM0pq2WEEt9h/8I5++YgkdC94rtsorb0CRvYweZcBkl4yoXSmIQY80WWhMGdCgdAN/OP2hvDM1rM/H5Vo0l7CPNMGJJ2kiC3oGRnMZlBFxJqIxMAfAfOQeyovkpKnzbzyjEmEj0/aa8vXkjN1mmjSMcZfU4WX174WIDlRmhZdyXJ5N2bPwXd3a9R3o5AQQ9Gjy7Dw5nMyOruKCbrEILUSCdYO83PryjO+ZhotSIMS9ucQJwYI0gWjYEsnv4ttYhUlvWxWbUI4zi7LLmi7mzvpDqLWA7Voqj4JtXnKdTAYXNMrl0lDH/nWk3FvvkAtWOnF6Ws5aYpQRPUab/WW4InFntGJH0=
    RABBITMQ_USER: AgAMkY9O0ulN1mjZrBmbGKQo7aPIqY62ZotJKPJNDt5xbkktAlv0xPZvaDHU/5q7X0JhjlwXbPttkVPjArNxe8bO4/Mnmwtk2b2rt1ZExYTU32TAtpL+1Q4jP0zERdb3clIohN8IdzfkPPTgx5mrHJPwoG8fQ8Hojl1dOjTJ0RysIXdTLpqCN0Ax/E9Vkc7FRV5mj491dyV+iI62dhavmLx31p/bzkv7D52lOooOgcXPG+LhHFavottjFeY0xrITx7PRRRGLYi44zN/mGW8KYVMZxLhQDhvUs4pEo30uDWU7NN2hUcUjKF3pBUWN7FGUMepIU+4Lc0bISoOSAXwZVJrkXQLeBg3SR5rYJIsgD9nDKOlJeLKiSg8g5maI8k83ZhmkTv/K9VdYWSUljE3w0p9nEORZ9ze1Hsi6A7HXk0Mcpg1gdNqpfT+BY5DFx/Ufzmfxw9SeNdumEytvD32QZWmTlfc2OCIqQmiYylxDRcqcSpvI4BFRD1gI6CxEGksk6yeujVmAOSnZezhi47czNniEZSlgD+8TsaSA+lyKJmAZAbW3l5DgQ6voPU1cY6ZQ/wg1/Oki2Iafli6Ks+zmrMfB5uuJpbeq/rkAMdQR7behIgZtT1jImLzbqXY38RvCqSRsljc+4YuLxKdg2k7JOqE8mkLO0XCWkwR8Mai9Sn7GrSGZ06VxyyC0fm2NykI7ulJA+Asxhwqs
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: billing
