---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: billing-db-credentials
  namespace: billing
spec:
  encryptedData:
    BILLING_DB_PASSWORD: AgBEEoKbxuFll/UU7kNCSWyxuM1i3bF6T2XjOCscxnSX7dNQOW7gFYM3ksMXw59Xn+I8bqKgDYK14cJpr097q+J/MReqOPHm74OT1lXgEB8jEAn4B8BBcb7y+vhoruIBxlT94QH8jXtvCtfmWTVtkj/EdkAQzE59cF04wVF08VxlzUqwV4DW2ViWFhp1uZw2bmm+65HIhxYq4PHj2G3U6XefpJo5Jz1uf+QNJToeNgL6AgUyGdGK3817xYGaFCdavNrtZo58vHxymMkz99NwKBUbPEgOkMs8dwhikCP8+F6nlVy3Lq8vn4YFsbCp6CFcKWv/akMCHVWASBFITf1vftHSfaBlH/aC4pgvkPgacxyc0AgNbIJyR3+Il/QoJd9fw2avZdaxHBi3hk+Rheg729y7e0bNH4/8YcyIxO99rLDJRsG4ZFoNq9h5RUP1tCFqlsuO1o24Ghzt+Cw1/o8JQVc+FtXTZkRDZpYdDOlsmDsM/SIqH1UOiiPSiQjb4GY1dw8lXH1Q37FTS0q/tNYOI25bkYZdvI/6lK+ggYv3eQd8q2X8Vs2LmOc19x+RxTj+Apwfj8ASplEtIcXx0Hu5Si8HzLobhKC4uz7TK3+lKR2Gxx0lq7m58SgdamZ6gJ60IETlmZM406CY5Fotzj33NT2wmXhSpnBfY8qF7VOnrpui2DWHi0E6ZmbAp95ypCUpKvpkrVwaVcSgiYjKZyBr7YIv9eV5gwym+g==
    BILLING_DB_USER: AgAG6kxlFzIFpxQRjlBh49mH12y4nZWlJVtrTbVXU0pvm8na3+Lj8ktFNeJFWP0pQhEhRk7pNvY8ob24qnKasafQtyd+ZW+v0op1hkPMs2pELkLt8+lnVwrpKs8AFRLnWDTxU+vqY2HzYL4JgD++h75MJ4LPdPvdA3YRZSJ7derSIkTud8j1iHVb7FlcekJ3bIVf4swRMr+4n83UtGi9BpHS4xcpGGX6uvk1vbj9OxNvelWy303d5rcd9pc0viVtC09U6+K0+xbNssx94v1/AXr9w+b0ody5bA8lWYfxYMjkY3meFifWqKbkG7jl1+4Owx4SmAGpyc/6mJOMnJV7rvxxwDbPZ1okUHnl5bsv7Jq2gdlOxNmhxvWjrRRrUGqBFYfh0TPm6PQwJUgp1iZnX0+vVX+SluF0ipm/byD0rcXJaMCDxvJ+K442umzMrsBfV1YtbfL4sf8172G80NFkB30ESX8Of5DAP9MxU9FXAC8gvFVkN0XH01k/Uwyb5DOALGp0KRCEFJO4GnJ24TVHsbxJWz+51oWc06NabakSQPD/YF26EzQA5bKfGT0LiHKUpeTM0hoqY8qRU3Kc62bjnjUg8n9hvaWc1ERWirlwtcFAciyoS0z+uFPcuFKGJtZeYFEspdFnP9g4XSUxFfjtRRMs+1sqcqFLnNSjIAEDKafr9F5tV0WjAdYYcvg3klw4vPeTWuSckv3b1miYC/0=
  template:
    metadata:
      creationTimestamp: null
      name: billing-db-credentials
      namespace: billing
