apiVersion: v1
kind: Secret
metadata:
  name: billing-app-secret
  namespace: default
type: Opaque
stringData:
  BILLING_DB_URL: "postgresql://billing_user:sdiene@billing-db:5432/billing_db"
  RABBITMQ_URL: "amqp://sdiene:sdiene@rabbitmq:5672"
  RABBITMQ_QUEUE: "billing_queue"
  RABBITMQ_PASSWORD: "sdiene"
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-app-secret
  namespace: default
type: Opaque
stringData:
  INVENTORY_DB_URL: "postgresql://inventory_user:sdiene@inventory-db:5432/inventory_db"
  RABBITMQ_URL: "amqp://sdiene:sdiene@rabbitmq:5672"
  RABBITMQ_QUEUE: "inventory_queue"
  RABBITMQ_PASSWORD: "sdiene"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
type: Opaque
stringData:
  BILLING_API_URL: "http://billing-app:8080"
  INVENTORY_API_URL: "http://inventory-app:8080"
  BILLING_SERVICE_URL: "http://billing-app:8080"
  INVENTORY_SERVICE_URL: "http://inventory-app:8080"
  RABBITMQ_URL: "amqp://sdiene:sdiene@rabbitmq:5672"
  RABBITMQ_QUEUE: "api_gateway_queue"
  RABBITMQ_PASSWORD: "sdiene"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "sdiene"