---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: api-gateway
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgAyf0mRmwaIQQQML+RUU0M4MOsiMQe+epO2BZ3pGSWN49gAm98Q9YT2ML+6vyPB9rlqkWPSql9k9mWC4RpdzoBaaPNFHh92Ku1znOtSqY8bEzp1M65749jhQzwP5kjjQfk9OYQbGkpB60r8mpFd8n4Jl+ZaN9UD9RNei0JVFU9V2CuMGhKuiaSR01HJ5qRtcUyZ7sQERPA0EbGqjr9/3MDPAKtjPUHri1+PL7ZUE//V5IlT83RxShZIDx2V2UK0amm9aa9AhAU6yS+AzjN4LFv2CE0GfvsBqg5E6yGsW3A5u+SHwRGBe8B18yw+T2RRkmTjorTtJTQ80Pn1F9b7s31/QNSuqK7EUPKkgBiLMj6GTphzDjdBiqLQyEvXzJlMo+WlkjXzbhIaqXLLoZG/9p6G9DfzcTk0X4PX0kg2FmQTcvtus7eitj0qqC12nsPa5DkI6837cTKoLZw72WIb2V/e24b2ueJNtlEpXLX4LdI0ObRZ/LhGDqKh4BUwV06y77ZGIRE6t6Pfnx+SfRale7var9fvCdmh06wA8ZAgBYlCFwMHfryGJBBdRxVAmnv0Hilt1bw2r+ZWi+ARGOdL/TjqRyXkWOZxaeChRIr3zG7KHRoSdaeVj3cNSQY949W54pk6BJ6FoU0gwhp6jV3iFd+klutK/q1aKSoQy1d1shYpKlbN1cPY7JQdpOUAdS/ZGe+p67ezMTwaiNeisfAEj1gPdLzbvKNb6wA=
    RABBITMQ_USER: AgBVAwjhiqxIl7gMapw/7jK+ZcXSrh1BhGL6jxdBlI1xleC4da6W1wKg6tOvhOxUCYYJwSmHgUCw4hxNXYmWp6NNxbOiFbcpbU/tZEhbWwv+YNfD9HofctzehlHyq7LhQDuqFx0iPwm9IjGMByKHxq32VW/iLC0KPZYNR6Tar9MWX8zXVRtIet4pqZ+qiKAsAWtZawEQDBCznK9luIRG2MPkUnXotbfpiZ3AaJwQoyI0bD8vqjSeAYVfQ9MuNKhEdFLb2NHVnR+oE65tZi/ZkAKGPKJvM+GPbBsrwmk38JpuDLm9h8zmI2mnVc++cKF3tTnCID6zTrAFKbE6eUrJmT8Pr9353dSToEEl9Pi0IIKjuZQPSYe03OCR5OWpWdEGh4bOuqjkTDh56jxyj1tcOkZq28VvhCYgShv+aBtFwFGEDf4hiS4Au1D77vJufRapkp0FEXaEbU+eUdFTPEDwn5JQBdwcYbrXSWADerX5XAHk0FBxi6GfFzCUTDd6Y1RHkMZ6e42dLVeMnHISXLITXCE0o8xenNvQusLExmzjljJt7B31pUo1s9n52Vqw9pX66B5I++nX/J3FWx+QkRIjXUQJlKYyoVMAydJokCCm1tfaVTYKqFNHpd3n233FdimhqgMAq3FBbNmjDdZVLA4L1qOYo6e76u12VISxreu42JfZaJoPL7SoY8liiB4Z6t/sMg/w5tuHHDud
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: api-gateway
