---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inventory-db-credentials
  namespace: inventory
spec:
  encryptedData:
    INVENTORY_DB_PASSWORD: AgCI8eRiFdcfZo/OKvEJHxjYQO85yntAm8OtWaiJ9ce3L58vRySs0hmAaCLShZnLrykijDXdbNloEoVPg7bBxnNvLNguVpzzhq4I/+g3kmK0lFzcKmmG7tkdy+9wkIRO5y1VvdwR0IB/WfhWwVnjEmi/69Hea/7tpBt0zjeqd5HZgde5qFqtPIOS9S7F2qec0nvkfOvZxtE+HEzcq+pyHcbZO2nkQvex0qXLhvHIX3TCzL5Vt32tLU7OfOtp6tSAhqmLDBX+8osgbNRIVokQs9BHaw+FP81qcfLwSh8caPRMlJvGA46gAu8kvtA/JEIUiZr1YWlGRXGjdjf9G+nNuwdp5jHRfPuwHQY8LGjQqIA5PvYf7teFsCzi96j5qdx2yj6x0y3/6aNaRttxuM3MgaEUja+ZuWkptQpDiMXHGJvENwoQbnyxDJwxNrGR8y3OG+d7jPnc6LA0RB83HGiu7Rx4nkkF9z+atj8MkwZUHOKyubq0Jy+ZiavFohWXR3Q5CscwcqjC1Jltv6Qi5F5y0uPaUU1RWODGQ7Y6VdEO2c1KV+Fzk5e2PMyXFULCk3DGi1Qdy3a371b4iT2ew0N7OO1UD2UzRSrCov8xyVA26d9N33DT8yc0nKwlpOrVeKcc0L11A7QWViEktj5c81PnZCTafzqr50QAHmKPhJrZKs483Pqk8xwzOoHie6LdAktQlXQuZVi6Nnds8SVooCiQCZ5K+F0fkpbLLfQ=
    INVENTORY_DB_USER: AgBj0Zrw6aHnEaNs4hM5JgZnpNBlf3WGBobapeou+UJm687bdqVlH/jL619Pp+V4SFjrVJWabUx7MAA2E3HI730Dw7ErbIof4YrBvDy4kXMiuLBHmrJ1t+0k/gTkhXEx1SLNrI9NXi6f6yn231Oq5uwX9CS+nlwO4iOG8lHyIzV+9Nc2/85tKd2oM6Jhc7j20hQO8Q93lchwm4C0mgxfUYMhZhlSCLY3pvOeyMsPjCMX+6SboyIdN9UQ5jaNinia+HA5fm6/K3lCOwrf1pKwLnM6DFVlaauFG/eycJ0aDrS3cKcCM4X6B6p6WaHLZKcDXFVsLEq2pJzqUhjR3bbH4r+MGjcxLahfH8eLfJ8oybOamdWI2EKGQir5t9GBoaU1IEZouW07Vomyn3eXuViDQsnATJhU1Oief9K9XbOBOsrBBYZHS5ZUrj8yzuUYUJRFFp1PDZxmMfF5Yxj5qVQYlrBGEKHtK0V+TxZ6PTo+bwPue5PnDh+G8oZ67wA8+e0XFLfbY+MHGxVcmgB77Aj9j9cfQbeQYNVgmCD6o78vHCom6/Iehyd24lXq8a7hh1HvOcFzK+3P3Hwj0Ktw4spOiZp9OuehZtyQG8OQwDpsKFPtsUsDm7M9C511VH+LD25KeOAMbk/Mt4ompqvqdiavTydzmOdyzh2vFnfeC8evlbIo+tSk+nq8b46B8wF0lHzzw2OzPsPwD21DvQ==
  template:
    metadata:
      creationTimestamp: null
      name: inventory-db-credentials
      namespace: inventory
